
- name: add standard exclude paths
  lineinfile:
    create: yes
    dest: /tmp/rsync-excludes
    line: "{{ item }}"
    state: present
  with_items:
  - .git
  - sites/default/files
  - sites/default/settings.php
  tags: codesync

- name: add configured exclude paths
  lineinfile:
    create: yes
    dest: /tmp/rsync-excludes
    line: "{{ item }}"
    state: present
  with_items: hot_directories
  tags: codesync

- name: sync static code
  sudo: yes
  sudo_user: "{{ dork_user }}"
  shell: >
    rsync -ru --delete
    --exclude-from=/tmp/rsync-excludes
    /var/source{{ docroot }}/ /var/web/
  tags: codesync

- name: link hot code directories
  file:
    src: /var/source{{ docroot }}/{{ item }}
    dest: /var/web/{{ item }}
    state: link
  with_items: hot_directories
  tags: codesync
